name: Build & Deploy

on:
  workflow_dispatch:
  schedule:
    - cron: '30 21 * * WED'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    permissions:
      pages: read
      contents: read

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/cache@v4.2.3
      with:
        path: ~/Steam_root
        key: "steam-cache"

    - name: Setup SteamCMD
      uses: Lordfirespeed/setup-steamcmd@v2.0.2

    - name: Populate SteamCMD profile config
      uses: Lordfirespeed/auth-steamcmd@v1.0.1
      with:
        steam_config_vdf: ${{ secrets.STEAM_CONFIG_VDF }}
        steam_username: ${{ secrets.STEAM_USERNAME }}

    - name: mkdir
      run: mkdir -p ~/Steam_root

    - name: Update Game
      run: steamcmd +@sSteamCmdForcePlatformType windows +force_install_dir ~/Steam_root +login ${{ secrets.STEAM_USERNAME }} +app_update 573090 +quit

    - uses: Swatinem/rust-cache@v2.7.8

    - uses: baptiste0928/cargo-install@v3.3.0
      with:
        crate: perseus-cli
        version: 0.4.2

    - id: get-url
      uses: TuftsRT/get-pages-url@v1.0.1

    - name: Perseus Export
      run: ROM_DIR=~/Steam_root/rom PERSEUS_BASE_PATH="${{ steps.get-url.outputs.url }}" perseus deploy -e --verbose

    - uses: actions/upload-pages-artifact@v3.0.1
      with:
        path: pkg/

  deploy:
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4.0.5
