name: Rust

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/cache@v4.2.3
      with:
        path: ~/Steam_root
        key: "steam-cache"

    - name: Setup SteamCMD
      uses: Lordfirespeed/setup-steamcmd@v2.0.2

    - name: Populate SteamCMD profile config
      uses: Lordfirespeed/auth-steamcmd@v1.0.1
      with:
        steam_config_vdf: ${{ secrets.STEAM_CONFIG_VDF }}
        steam_username: ${{ secrets.STEAM_USERNAME }}

    - name: mkdir
      run: mkdir -p ~/Steam_root

    - name: Update Game
      run: steamcmd +@sSteamCmdForcePlatformType windows +force_install_dir ~/Steam_root +login ${{ secrets.STEAM_USERNAME }} +app_update 573090 +quit

    - name: pwd
      run: pwd
    - name: tree
      run: tree ~/Steam_root
    
    - uses: baptiste0928/cargo-install@v3.3.0
      with:
        crate: perseus-cli
        version: 0.4.2
